steps:
    # Install dependencies
    - name: node
      entrypoint: npm
      args: ['install']
    # Build the app
    - name: node
      entrypoint: npm
      args: ['run', 'build']
    # Deploy only hosting to Firebase
    - name: gcr.io/streaming-analytics-showcase/firebase
      args: ['deploy', '--project=streaming-analytics-showcase', '--only=hosting']
      env:
        - 'VUE_APP_FIREBASE_API_KEY=${_VUE_APP_FIREBASE_API_KEY}'
        - 'VUE_APP_FIREBASE_APP_ID=${_VUE_APP_FIREBASE_APP_ID}'
        - 'VUE_APP_FIREBASE_AUTH_DOMAIN=${_VUE_APP_FIREBASE_AUTH_DOMAIN}'
        - 'VUE_APP_FIREBASE_DATABASE_URL=${_VUE_APP_FIREBASE_DATABASE_URL}'
        - 'VUE_APP_FIREBASE_MESSAGE_SENDER_ID=${_VUE_APP_FIREBASE_MESSAGE_SENDER_ID}'
        - 'VUE_APP_FIREBASE_PROJECT_ID=${_VUE_APP_FIREBASE_PROJECT_ID}'